[package]
name = "mediacorral-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
tokio = { version = "1.45.1", features = ["full"] }
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"
