syntax = "proto3";
package mediacorral.drive_coordinator.v1;

service DriveCoordinatorService {
  // Establishes a connection between the drive and the coordinator, allowing
  // the coordinator to send commands back to the drive, which may live on
  // another network entirely.
  rpc ConnectDrive(stream DriveConnectionRequest) returns (stream DriveConnectionResponse);

  // Finalizes a rip job, uploading media if the drive controller doesn't use a
  // shared filesystem.
  //
  // The drive controller, when finalizing a rip job, must first send a
  // `header` message. This message includes information about the operations
  // that are about to take place. Along with the ID of the rip job, it should
  // also contain a list of files to be uploaded, including their name and
  // size. This list must be in the order that the files will be uploaded.
  //
  // Next, the drive controller should send file data in `data_chunk` objects.
  // These objects may contain up to 3MB of data from the file, and should be
  // transmitted in the order they appear in the file.
  //
  // Finally, in order to finish the upload, the drive controller must send an
  // `md5_hash` object. This terminates the upload and begins the next file,
  // if another file is to be uploaded. The number of `md5_hash` objects must
  // equal the number of `upload_files` objects in the `header`.
  //
  // Once all files have been fully uploaded, the coordinator may return with
  // a list of corrupted files. This indicates that the rip job is still
  // incomplete, and the drive controller should call the RPC function again,
  // uploading the files that the coordinator indicated were corrupted.
  //
  // If the coordinator responds with an empty list of `corrupted_files`, then
  // the rip job is considered complete, and may be forgotten by the drive
  // controller.
  rpc FinalizeRipJob(stream FinalizeRipJobRequest) returns (FinalizeRipJobResponse);
}

// Messages sent from the drive to the coordinator
message DriveConnectionRequest {
  oneof message {
    DiscoveryInfo discovery = 1;
    DriveStatus drive_status_update = 2;
    RipStatus rip_status_update = 3;
  }
}

// Contains identifying information about the drive, to be sent immediately
// upon connection.
//
// The coordinator will ignore any messages received before this one.
message DiscoveryInfo {
  string drive_id = 1;
  string drive_name = 2;
}

// Provides a status update for the drive
message DriveStatus {
  DriveStatusTag status = 1;
  optional string disc_name = 2;
  optional int64 active_rip_job = 3;
}

enum DriveStatusTag {
  DRIVE_STATUS_TAG_UNSPECIFIED = 0;
  DRIVE_STATUS_TAG_EMPTY = 1;
  DRIVE_STATUS_TAG_TRAY_OPEN = 2;
  DRIVE_STATUS_TAG_NOT_READY = 3;
  DRIVE_STATUS_TAG_DISC_LOADED = 4;
}

// Provides a status update for the specified rip job
message RipStatus {
  int64 rip_job = 1;
  RipStatusTag status = 2;

  string cprog_title = 3;
  string tprog_title = 4;
  uint32 cprog_value = 5;
  uint32 tprog_value = 6;
  uint32 max_prog_value = 7;

  repeated string logs = 8;
}

enum RipStatusTag {
  RIP_STATUS_TAG_UNSPECIFIED = 0;
  RIP_STATUS_TAG_RUNNING = 1;
  RIP_STATUS_TAG_COMPLETED = 2;
  RIP_STATUS_TAG_ERROR = 4;
}

// Messages sent from the coordinator to the drive
message DriveConnectionResponse {
  oneof message {
    TrayCommand tray_command = 1;
    RipMediaCommand rip_media = 2;
  }
}

// A command for the disc tray to execute
enum TrayCommand {
  TRAY_COMMAND_UNSPECIFIED = 0;
  TRAY_COMMAND_OPEN_TRAY = 1;
  TRAY_COMMAND_CLOSE_TRAY = 2;
}

message RipMediaCommand {
  // The ID for the rip job, as used in the database
  int64 job_id = 1;
  // Whether or not to automatically eject the drive upon completion
  bool autoeject = 2;
}

message FinalizeRipJobRequest {
  oneof message {
    // Contains metadata about the file being uploaded
    FinalizeRipJobRequestHeader header = 1;

    // Contains up to 3MB of data from the file
    bytes data_chunk = 2;

    // Contains a hash of the most recent file to verify its integrity.
    bytes md5_hash = 3;
  }
}

message FinalizeRipJobRequestHeader {
  // The ID for the rip job, as used in the database
  int64 rip_job = 1;

  // A list of files to be uploaded, in the order they will be uploaded.
  repeated FileDescription upload_files = 2;
}

message FileDescription {
  // The name of the file to be uploaded
  string file_name = 1;

  // The size in bytes of the file being uploaded.
  // This is used only as a progress indicator, and should
  // not be relied upon. A value of `0` means the file is
  // of indeterminate size.
  uint64 file_size = 2;
}

message FinalizeRipJobResponse {
  repeated string corrupted_files = 1;
}
