/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DriveMonitor: typeof import('./components/DriveMonitor.vue')['default']
    ManualMatchDialog: typeof import('./components/ManualMatchDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspicionDialog: typeof import('./components/SuspicionDialog.vue')['default']
  }
}
