@startuml
component "Media Servers" as mediaservers

component "Shared Filesystem" as fs {
	folder "Rips" as rips
	folder "Blobs" as blobs
	folder "Exports" as exports
}

component "Mediacorral" as mc {
	top to bottom direction

	component "Drive Controllers" as drive_controllers {
		node "Drive Controller 1" {
			() "BD Drive" as dc1_bd
			component "Controller" as dc1
			dc1 <-left-> dc1_bd
		}
		node "Drive Controller 2" {
			() "BD Drive" as dc2_bd
			component "Controller" as dc2
			dc2 <-left-> dc2_bd
		}
		node "Drive Controller 3" {
			() "BD Drive" as dc3_bd
			component "Controller" as dc3
			dc3 <-left-> dc3_bd
		}
		note as N1
			Drive controllers use makemkvcon to rip DVDs & blu-rays,
			and save them to the "Rips" directory, then fire off a
			notification to the coordinator that the job is complete.
		end note
		N1 .up[hidden]. dc1
		N1 .up[hidden]. dc2
		N1 .up[hidden]. dc3
	}

	component "Coordinator" as coord

	component "Web Client" as client
	client -right-> coord : grpc-web

	component "Workers" as workers {
		component "Worker 1" as w1
		component "Worker 2" as w2
		component "Worker 3" as w3
		note as N2
			Workers use a variety of tools to extract & transform
			information from the mkv files. Then, they write the
			changes back into the database.
		end note
	}

	w1 -down-> coord
	w2 -down-> coord
	w3 -down-> coord
	coord <-down-> dc1
	coord <-down-> dc2
	coord <-down-> dc3
}

mediaservers -up-> exports : Media files
drive_controllers -left-> rips : MakeMKV work directories
workers <-left-> blobs : Source files & artifacts
coord -left-> exports : Media exports

@enduml
