shared_directory: /home/shaunkeys/mediacorral_testing
serve_address: 127.0.0.1:5502
coordinator_address: 127.0.0.1:5501
controller_id: main
drives:
- name: Top
  path: /dev/sr1
- name: Bottom
  path: /dev/sr0
